spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://192.168.43.155:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
      - id: auth_util
        uri: lb://AUTH-GESTION-UTILISATEUR  #
        predicates:
        - Path=/api/auth_util/**
      - id: role
        uri: lb://AUTH-GESTION-UTILISATEUR #
        predicates:
        - Path=/api/role/**
      - id: message
        uri: lb://MESSAGE #
        predicates:
        - Path=/api/message/**
      - id: role
        uri: lb://product-service
        predicates:
        - Path=/api/role/**
      - id: offer
        uri: lb://OFFRE-PRODUIT #
        predicates:
        - Path=/api/offer/**
      - id: product
        uri: lb://OFFRE-PRODUIT #
        predicates:
        - Path=/api/product/**
      - id: product
        uri: lb://OFFRE-PRODUIT #
        predicates:
        - Path=/api/request/**
      - id: social
        uri: lb://NOTATION-COMMENTAIRE #
        predicates:
        - Path=/api/comments/**
      - id: commande
        uri: lb://COMMANDE #
        predicates:
        - Path=/api/commande/**
      
server:
    address: 192.168.43.13 
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

      

