server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Active la découverte automatique des services via Eureka
          lower-case-service-id: true
