server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false  # ← Désactivé
      routes:
        - id: message
          uri: lb://MESSAGE # Nom exact du service dans Eureka
          predicates:
            - Path=/api/message/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true